Add support for validating the hd claim
imkira/gcp-iap-auth pull request #21
Opened 2021-07-15 14:49 UTC by neuroid

2021-09-24 13:23 UTC, neuroid commented
Hi @imkira. Any interest in merging this?

2021-09-25 11:19 UTC, imkira requested changes

2021-09-25 11:19 UTC, imkira commented on config.go
> +	domains        = flag.String("domains", "", "Comma-separated list of allowed JWT hd claims (optional)")
nit: I would write `Hosted Domains (hd)` instead

2021-09-25 11:20 UTC, imkira commented
@neuroid thanks for the contribution. Looks good. Just have a minor comment regarding the flag description.
Cheers.

2021-09-26 20:06 UTC, neuroid commented on config.go
> +	domains        = flag.String("domains", "", "Comma-separated list of allowed JWT hd claims (optional)")
Sure

2021-10-22 12:14 UTC, neuroid commented
@imkira 👋

2021-10-22 14:27 UTC, imkira approved these changes

2021-10-22 14:28 UTC, imkira commented
Thanks for pinging me and apologies for the delay. Once again thanks for the contribution!

2021-10-22 14:28 UTC, merged